name: 'Cloudflare DNS LetsEncrypt Certificate Generator'
description: 'Generating LetsEncrypt certificate with DNS challenge for domains parked in Cloudflare'
author: 'Shibly Meeran'
inputs:
  cloudflare_dns_api_token:
    description: 'Cloudflare DNS API token with Zone:DNS:Edit permission'
  domain_name:
    description: 'The fully qualified domain name for which certificate is required'
  email:
    description: 'Email address (to notify on certificate expiry)'
  certs_file_name:
    description: 'The name of file in which the generated keys and certificates will be stored'
    default: "certs"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cloudflare_dns_api_token }}
    - ${{ inputs.domain_name }}
    - ${{ inputs.email }}
    - ${{ inputs.certs_file_name }}