name: Cloudflare LetsEncrypt Certbot test
on: [push]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Performing a dry-run test
      uses: ./
      with:
        cloudflare_dns_api_token: ${{ secrets.CLOUDFLARE_DNS_API_TOKEN }}
        domain_name: ${{ secrets.DOMAIN_NAME }}
        email: ${{ secrets.EMAIL }}
        certs_file_name: my_certs
        dry_run: true